kaltura/playkit-js-kaltura-cuepoints

- package.json
- src/cuepoint-service.ts
- src/global.d.ts
- src/providers/live/live-provider.ts
- src/providers/provider.ts
- src/providers/vod-provider.ts
- src/providers/vod/response-types/kaltura-cue-point-list-response.ts
- src/providers/vod/response-types/kaltura-cue-point.ts
- src/providers/vod/response-types/kaltura-thumb-cue-point.ts
- src/providers/vod/thumb-loader.ts
- src/providers/vod/vod-provider.ts
- yarn.lock
implement VOD provider
solves FEV-993
> feat(FEV-993): implement VOD provider

- src/providers/provider.ts
- src/providers/vod/vod-provider.ts
player setSource calls change_source_ended just before merging the session to the config.
Therefore we need to postpone the ks retrieval till after the callback returns
> fix(FEV-993): move ks retrieval till after callback

- src/providers/live/live-provider.ts
- src/providers/utils.ts
- src/providers/vod/vod-provider.ts
get the service Url from Kaltura player (which get it from provider)
solves FEC-11608
related pr: 
https://github.com/kaltura/playkit-js-providers/pull/157
> feat(FEC-11608): Provider - Expose default service Url

- src/providers/live/live-provider.ts
- src/providers/provider.ts
- src/providers/vod/vod-provider.ts
- test/src/providers/live/live-provider.spec.js
pass `CuePoint` to addCuePoints api
Depends on https://github.com/kaltura/kaltura-player-js/pull/512
> feat(FEC-11761): expose stream timed metadata - phase 2

- src/providers/vod/vod-provider.ts
set default time for view-change cue-points
> fix(FEV-1142): Wrong layout when using DVR and slides appears not from beginning of media

- src/providers/vod/vod-provider.ts
fix end time for cues with same start-end time
> fix(FEV-1085): only first cue point with same end\start time become active 

- src/providers/vod/vod-provider.ts
use 1s as quiz-cue points duration
> feat(FEV-1035): quiz cue-points end-time

- src/providers/live/live-provider.ts
- src/providers/utils.ts
- src/providers/vod/vod-provider.ts
- test/src/providers/utils.spec.js
- add advanced sort of cue-points;
- increase test coverage;
> fix(FEV-1197): When there are multiple questions at the same time- the order is random and not by creation time in KIA

- src/providers/utils.ts
- src/providers/vod/vod-provider.ts
use different que-point duration for Safari and other browsers;
> fix(FEV-1225): most of the times the first quiz (00:00:00) is not presented to the user (video will pass that point)

- src/cuepoint-service.ts
- src/cuepoints.ts
- src/providers/live/live-provider.ts
- src/providers/utils.ts
- src/providers/vod/vod-provider.ts
- src/types.ts
- test/src/providers/live/live-provider.spec.js
- test/src/providers/utils.spec.js
use 'player.shouldAddKs' method to define if KS needed
> fix(FEV-1249): Kaltura CuePoints loads thumb assets always with KS

- src/providers/vod/vod-provider.ts
execute ThumbUrlLoader only if assetId exist
> fix(FEV-1262): ThumbUrlLoader fails multi-request if assetId doesn't defined

- src/cuepoint-manager/cuepoint-engine.ts
- src/cuepoint-manager/cuepoint-manager.ts
- src/cuepoint-manager/index.ts
- src/cuepoint-service.ts
- src/providers/provider.ts
- src/types.ts
- yarn.lock
- text-track features doesn't work correctly in `youtube` media type. For such cases cue-point manager uses custom cue-point engine that tracks `time-update` event of player, find active cue-points and dispatches `TIMED_METADATA_ADDED` and `TIMED_METADATA_CHANGE` events;
- updated KalturaPlayer dependency;
> fix(FEV-1291): custom cue-point engine

- src/providers/live/live-provider.ts
cue-point plugin trying to get base asset url for thumb cues one-by-one until base asset url fetched
> fix(FEV-1322): slides that were broadcasted prior to the archive will appear without image in the navigation plugin

- src/providers/live/live-provider.ts
filter out cues from previous live session
> fix(FEV-1322): slides that were broadcasted prior to the archive will appear in the navigation plugin

- src/providers/vod/vod-provider.ts
> fix(FEV-1597): handle non-external text tracks

- package.json
- src/providers/live/push-notifications-provider.ts
- yarn.lock
solves: https://kaltura.atlassian.net/browse/SUP-34892
1) upd logic of generation user id;
2) use es6 modules import;
> fix(SUP-34892): When users send private messages their names appears incorrect in WC app.

- .github/workflows/run_tests.yaml
- karma.conf.js
> chore: add tests

- src/cuepoint-service.ts
need to reset `_isPreventSeekActive` flag.
Solves FEC-13780
> fix(FEC-13780): reset _isPreventSeekActive

- src/providers/live/live-provider.ts
- src/providers/provider.ts
- src/providers/vod/index.ts
- src/providers/vod/vod-provider.ts
Reverts kaltura/playkit-js-kaltura-cuepoints#62
> Revert "handle slide cuepoints in simulive"

- src/providers/live/live-provider.ts
Fetch simulive cuepoints for pre and post playback parts as well
Resolves FEC-13789
> fix(FEC-13789): show hotspots for pre and post entries

- src/providers/common/hotspot-loader.ts
- src/providers/common/index.ts
- src/providers/common/thumb-loader.ts
- src/providers/live/live-provider.ts
- src/providers/provider.ts
- src/providers/vod/index.ts
- src/providers/vod/vod-provider.ts
Call api to get slide cuepoints
Refactor providers to reuse logic from vod provider for simulive entries
Add an offset to the cues according to the clip start
Resolves FEC-13731
> feat(FEC-13731): Slides on simulive

- src/providers/dataAggregator.ts
- src/providers/live/live-provider.ts
- src/providers/provider.ts
- test/src/providers/live/live-provider.spec.js
Reverts kaltura/playkit-js-kaltura-cuepoints#68
> Revert "Revert "fix(FEC-13766): last active slide does not appear on dual screen""

- src/providers/live/live-provider.ts
resolves: https://kaltura.atlassian.net/browse/FEC-13905
For user QNA cues show all cues out of live-edge
> fix(FEC-13905): don't use data aggregator for user QNA cues

- src/providers/provider.ts
issue:
quiz with prevent seek plugin cause that "quiz complete" message was showen on screen before take the quiz.
solution:
if the video type is quiz then don't use pending cuepoints.
solve [SUP-44820](https://kaltura.atlassian.net/browse/SUP-44820)
[SUP-44820]: https://kaltura.atlassian.net/browse/SUP-44820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-44820): Video Quiz not working

- src/providers/vod/vod-provider.ts
- src/types.ts
example of usage
`this.cuePointManager.registerTypes([this.cuePointManager.CuepointType.SUMMARY]);`
> fix(FEC-14320): add "summary" type of data
